# Generated by Django 4.1.2 on 2022-10-30 18:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default=uuid.UUID('53de1e7a-5495-40cd-8558-9dd5d6595baf'), editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.CharField(default=uuid.UUID('53de1e7a-5495-40cd-8558-9dd5d6595baf'), editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='id',
            field=models.CharField(default=uuid.UUID('53de1e7a-5495-40cd-8558-9dd5d6595baf'), editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
