# Generated by Django 4.1.2 on 2022-10-30 18:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_author_id_alter_book_id_alter_publisher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default=uuid.UUID('da26d347-6832-4423-ae2d-2b2579964a00'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.CharField(default=uuid.UUID('da26d347-6832-4423-ae2d-2b2579964a00'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='id',
            field=models.CharField(default=uuid.UUID('da26d347-6832-4423-ae2d-2b2579964a00'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
