# Generated by Django 4.1.2 on 2022-10-30 18:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_author_id_alter_book_id_alter_publisher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default=uuid.UUID('4cd2eac4-c90c-47d8-acd7-ec2abab80020'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.CharField(default=uuid.UUID('4cd2eac4-c90c-47d8-acd7-ec2abab80020'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='id',
            field=models.CharField(default=uuid.UUID('4cd2eac4-c90c-47d8-acd7-ec2abab80020'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
